management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include: ping,diskSpace
        readiness:
          include: ping,db,diskSpace
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ecommercedb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:ecommerceuser}
    password: ${SPRING_DATASOURCE_PASSWORD:ecommercepass}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ecommerce-docker
      auto-offset-reset: earliest

logging:
  level:
    com.example.ecommerce: INFO
